// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	t.Skip("edit main_test.go with your sample input before debugging")
}

func TestSamples(t *testing.T) {
	t.Skip("edit main_test.go with your sample input before debugging")
}
