// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "fmt"

func main() {
	aliceSizes := []int{1, 1}
	bobSizes := []int{2, 2}
	got := fairCandySwap(aliceSizes, bobSizes)
	fmt.Printf("got = %#v", got)
}
