// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	aliceSizes := []int{1, 1}
	bobSizes := []int{2, 2}
	got := fairCandySwap(aliceSizes, bobSizes)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		aliceSizes := []int{1, 1}
		bobSizes := []int{2, 2}
		got := fairCandySwap(aliceSizes, bobSizes)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		aliceSizes := []int{1, 2}
		bobSizes := []int{2, 3}
		got := fairCandySwap(aliceSizes, bobSizes)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		aliceSizes := []int{2}
		bobSizes := []int{1, 3}
		got := fairCandySwap(aliceSizes, bobSizes)
		t.Logf("got = %#v", got)
	})
}
