// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	s := "ADOBECODEBANC"
	t := "ABC"
	got := minWindow(s, t)
	fmt.Printf("got = %#v", got)
}
