// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums1 := []int{1, 2, 3, 2, 1}
	nums2 := []int{3, 2, 1, 4, 7}
	got := findLength(nums1, nums2)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums1 := []int{1, 2, 3, 2, 1}
		nums2 := []int{3, 2, 1, 4, 7}
		got := findLength(nums1, nums2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums1 := []int{0, 0, 0, 0, 0}
		nums2 := []int{0, 0, 0, 0, 0}
		got := findLength(nums1, nums2)
		t.Logf("got = %#v", got)
	})
}
