// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func TestDebug(t *testing.T) {
	head := buildListNode([]int{1, 4, 3, 2, 5, 2})
	x := 3
	got := partition(head, x)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		head := buildListNode([]int{1, 4, 3, 2, 5, 2})
		x := 3
		got := partition(head, x)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		head := buildListNode([]int{2, 1})
		x := 2
		got := partition(head, x)
		t.Logf("got = %#v", got)
	})
}
