// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	height := []int{1, 8, 6, 2, 5, 4, 8, 3, 7}
	got := maxArea(height)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		height := []int{1, 8, 6, 2, 5, 4, 8, 3, 7}
		got := maxArea(height)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		height := []int{1, 1}
		got := maxArea(height)
		t.Logf("got = %#v", got)
	})
}
