// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	n := 5
	got := findIntegers(n)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		n := 5
		got := findIntegers(n)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		n := 1
		got := findIntegers(n)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		n := 2
		got := findIntegers(n)
		t.Logf("got = %#v", got)
	})
}
