// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "fmt"

func main() {
	words := []string{"Hello", "Alaska", "Dad", "Peace"}
	got := findWords(words)
	fmt.Printf("got = %#v", got)
}
