// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	words := []string{"Hello", "Alaska", "Dad", "Peace"}
	got := findWords(words)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		words := []string{"Hello", "Alaska", "Dad", "Peace"}
		got := findWords(words)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		words := []string{"omk"}
		got := findWords(words)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		words := []string{"adsdf", "sfd"}
		got := findWords(words)
		t.Logf("got = %#v", got)
	})
}
