// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums1 := []int{4, 1, 2}
	nums2 := []int{1, 3, 4, 2}
	got := nextGreaterElement(nums1, nums2)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums1 := []int{4, 1, 2}
		nums2 := []int{1, 3, 4, 2}
		got := nextGreaterElement(nums1, nums2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums1 := []int{2, 4}
		nums2 := []int{1, 2, 3, 4}
		got := nextGreaterElement(nums1, nums2)
		t.Logf("got = %#v", got)
	})
}
