// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	heights := []int{2, 1, 5, 6, 2, 3}
	got := largestRectangleArea(heights)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		heights := []int{2, 1, 5, 6, 2, 3}
		got := largestRectangleArea(heights)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		heights := []int{2, 4}
		got := largestRectangleArea(heights)
		t.Logf("got = %#v", got)
	})
}
