// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import (
	"testing"
)

func TestDebug(t *testing.T) {
	board := [][]byte{{'5', '3', '.', '.', '7', '.', '.', '.', '.'}, {'6', '.', '.', '1', '9', '5', '.', '.', '.'}, {'.', '9', '8', '.', '.', '.', '.', '6', '.'}, {'8', '.', '.', '.', '6', '.', '.', '.', '3'}, {'4', '.', '.', '8', '.', '3', '.', '.', '1'}, {'7', '.', '.', '.', '2', '.', '.', '.', '6'}, {'.', '6', '.', '.', '.', '.', '2', '8', '.'}, {'.', '.', '.', '4', '1', '9', '.', '.', '5'}, {'.', '.', '.', '.', '8', '.', '.', '7', '9'}}
	solveSudoku(board)

	t.Log("--- Solved Sudoku Board ---")
	for i := 0; i < len(board); i++ {
		// Print horizontal grid line every 3 rows
		if i > 0 && i%3 == 0 {
			t.Log("------+-------+------")
		}

		// Build the row string with vertical separators
		var rowStr string
		for j := 0; j < len(board[i]); j++ {
			if j > 0 && j%3 == 0 {
				rowStr += "| "
			}
			rowStr += string(board[i][j]) + " "
		}

		t.Log(rowStr)
	}
	t.Logf("function executed")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		board := [][]byte{{'5', '3', '.', '.', '7', '.', '.', '.', '.'}, {'6', '.', '.', '1', '9', '5', '.', '.', '.'}, {'.', '9', '8', '.', '.', '.', '.', '6', '.'}, {'8', '.', '.', '.', '6', '.', '.', '.', '3'}, {'4', '.', '.', '8', '.', '3', '.', '.', '1'}, {'7', '.', '.', '.', '2', '.', '.', '.', '6'}, {'.', '6', '.', '.', '.', '.', '2', '8', '.'}, {'.', '.', '.', '4', '1', '9', '.', '.', '5'}, {'.', '.', '.', '.', '8', '.', '.', '7', '9'}}
		solveSudoku(board)
		t.Logf("function executed")
	})
}
