// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

type ListNode struct {
	Val  int
	Next *ListNode
}

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func printListNode(head *ListNode) {
	for p := head; p != nil; p = p.Next {
		fmt.Printf("%d,\t", p.Val)
	}
	fmt.Println()
}

func main() {
	head := buildListNode([]int{1, 2, 3, 4, 5})
	fmt.Println("\n=====================")
	k := 2
	got := reverseKGroup(head, k)
	printListNode(got)
}
