// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	height := []int{0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1}
	got := trap(height)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		height := []int{0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1}
		got := trap(height)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		height := []int{4, 2, 0, 3, 2, 5}
		got := trap(height)
		t.Logf("got = %#v", got)
	})
}
