// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	matrix := [][]byte{{'1', '0', '1', '0', '0'}, {'1', '0', '1', '1', '1'}, {'1', '1', '1', '1', '1'}, {'1', '0', '0', '1', '0'}}
	got := maximalRectangle(matrix)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		matrix := [][]byte{{'1', '0', '1', '0', '0'}, {'1', '0', '1', '1', '1'}, {'1', '1', '1', '1', '1'}, {'1', '0', '0', '1', '0'}}
		got := maximalRectangle(matrix)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		matrix := [][]byte{{'0'}}
		got := maximalRectangle(matrix)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		matrix := [][]byte{{'1'}}
		got := maximalRectangle(matrix)
		t.Logf("got = %#v", got)
	})
}
