// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

type ListNode struct {
	Val  int
	Next *ListNode
}

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func main() {
	lists := []*ListNode{buildListNode([]int{1, 4, 5}), buildListNode([]int{1, 3, 4}), buildListNode([]int{2, 6})}
	got := mergeKLists(lists)
	fmt.Printf("got = %#v", got)
}
