// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func buildTreeNode(values []any) *TreeNode {
	if len(values) == 0 || values[0] == nil {
		return nil
	}

	root := &TreeNode{Val: values[0].(int)}
	queue := []*TreeNode{root}
	index := 1

	for len(queue) > 0 && index < len(values) {
		node := queue[0]
		queue = queue[1:]

		if index < len(values) && values[index] != nil {
			node.Left = &TreeNode{Val: values[index].(int)}
			queue = append(queue, node.Left)
		}
		index++

		if index < len(values) && values[index] != nil {
			node.Right = &TreeNode{Val: values[index].(int)}
			queue = append(queue, node.Right)
		}
		index++
	}

	return root
}

func main() {
	root := buildTreeNode([]any{1, 2, 3})
	got := maxPathSum(root)
	fmt.Printf("got = %#v", got)
}
