// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func buildTreeNode(values []any) *TreeNode {
	if len(values) == 0 || values[0] == nil {
		return nil
	}

	root := &TreeNode{Val: values[0].(int)}
	queue := []*TreeNode{root}
	index := 1

	for len(queue) > 0 && index < len(values) {
		node := queue[0]
		queue = queue[1:]

		if index < len(values) && values[index] != nil {
			node.Left = &TreeNode{Val: values[index].(int)}
			queue = append(queue, node.Left)
		}
		index++

		if index < len(values) && values[index] != nil {
			node.Right = &TreeNode{Val: values[index].(int)}
			queue = append(queue, node.Right)
		}
		index++
	}

	return root
}

func TestDebug(t *testing.T) {
	root := buildTreeNode([]any{1, 2, 3})
	got := maxPathSum(root)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		root := buildTreeNode([]any{1, 2, 3})
		got := maxPathSum(root)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		root := buildTreeNode([]any{-10, 9, 20, nil, nil, 15, 7})
		got := maxPathSum(root)
		t.Logf("got = %#v", got)
	})
}
