// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	prices := []int{3, 3, 5, 0, 0, 3, 1, 4}
	got := maxProfit(prices)
	fmt.Printf("got = %#v", got)
}
