// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func main() {
	head := buildListNode([]int{4, 2, 1, 3})
	got := insertionSortList(head)
	fmt.Printf("got = %#v", got)
}
