// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func TestDebug(t *testing.T) {
	head := buildListNode([]int{4, 2, 1, 3})
	got := insertionSortList(head)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		head := buildListNode([]int{4, 2, 1, 3})
		got := insertionSortList(head)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		head := buildListNode([]int{-1, 5, 3, 4, 0})
		got := insertionSortList(head)
		t.Logf("got = %#v", got)
	})
}
