// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "fmt"

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func main() {
	l1 := buildListNode([]int{2, 4, 3})
	l2 := buildListNode([]int{5, 6, 4})
	got := addTwoNumbers(l1, l2)
	fmt.Printf("got = %#v", got)
}
