// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func buildListNode(values []int) *ListNode {
	var head *ListNode
	var tail *ListNode
	for _, value := range values {
		node := &ListNode{Val: value}
		if head == nil {
			head = node
			tail = node
			continue
		}
		tail.Next = node
		tail = node
	}
	return head
}

func TestDebug(t *testing.T) {
	l1 := buildListNode([]int{2, 4, 3})
	l2 := buildListNode([]int{5, 6, 4})
	got := addTwoNumbers(l1, l2)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		l1 := buildListNode([]int{2, 4, 3})
		l2 := buildListNode([]int{5, 6, 4})
		got := addTwoNumbers(l1, l2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		l1 := buildListNode([]int{0})
		l2 := buildListNode([]int{0})
		got := addTwoNumbers(l1, l2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		l1 := buildListNode([]int{9, 9, 9, 9, 9, 9, 9})
		l2 := buildListNode([]int{9, 9, 9, 9})
		got := addTwoNumbers(l1, l2)
		t.Logf("got = %#v", got)
	})
}
