// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	nums := []int{4, 3, 2, 6}
	got := maxRotateFunction(nums)
	fmt.Printf("got = %#v", got)
}
