// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums := []int{4, 3, 2, 6}
	got := maxRotateFunction(nums)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums := []int{4, 3, 2, 6}
		got := maxRotateFunction(nums)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums := []int{100}
		got := maxRotateFunction(nums)
		t.Logf("got = %#v", got)
	})
}
