#!/usr/bin/env python3

import json
import re
import subprocess
import sys
from pathlib import Path

AUTO_MARKER = "// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat"
PLACEHOLDER_SKIP = 't.Skip("edit main_test.go with your sample input before debugging")'


def split_top_level(text: str) -> list[str]:
    parts = []
    current = []
    depth = 0
    for ch in text:
        if ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(ch)
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parse_signature(main_go: Path):
    content = main_go.read_text()
    match = re.search(r"^func\s+([A-Za-z_]\w*)\((.*?)\)\s*([^{\n]*)\{", content, re.M | re.S)
    if not match:
        raise SystemExit(f"could not find function signature in {main_go}")

    func_name = match.group(1)
    params_raw = match.group(2).strip()
    return_type = match.group(3).strip()
    params = []

    if params_raw:
        for chunk in split_top_level(params_raw):
            if not chunk:
                continue
            name_part, type_part = chunk.rsplit(" ", 1)
            for name in [n.strip() for n in name_part.split(",")]:
                if name:
                    params.append((name, type_part.strip()))

    return func_name, params, return_type


def parse_cases(test_data: Path, arity: int):
    lines = [line.strip() for line in test_data.read_text().splitlines() if line.strip()]
    if arity == 0:
        return [[]]
    if len(lines) % arity != 0:
        raise SystemExit(
            f"{test_data} has {len(lines)} non-empty lines, which is not divisible by arity {arity}"
        )
    return [lines[i : i + arity] for i in range(0, len(lines), arity)]


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def byte_literal(value):
    if isinstance(value, str):
        if len(value) == 1:
            return repr(value)
        return f"byte({go_string(value)})"
    return str(value)


def go_literal(value, go_type: str) -> str:
    if go_type in {"int", "int32", "int64", "uint", "uint32", "uint64"}:
        return str(value)
    if go_type in {"float32", "float64"}:
        return repr(value)
    if go_type == "bool":
        return "true" if value else "false"
    if go_type == "string":
        return go_string(value)
    if go_type == "byte":
        return byte_literal(value)
    if go_type == "[]byte":
        if isinstance(value, str):
            return f"[]byte({go_string(value)})"
        return "[]byte{" + ", ".join(byte_literal(v) for v in value) + "}"
    if go_type == "[][]byte":
        rows = []
        for row in value:
            rows.append("{" + ", ".join(byte_literal(v) for v in row) + "}")
        return "[][]byte{" + ", ".join(rows) + "}"
    if go_type.startswith("[][]"):
        inner = go_type[4:]
        rows = []
        for row in value:
            rows.append("{" + ", ".join(go_literal(v, inner) for v in row) + "}")
        return f"{go_type}{{" + ", ".join(rows) + "}"
    if go_type.startswith("[]"):
        inner = go_type[2:]
        return f"{go_type}{{" + ", ".join(go_literal(v, inner) for v in value) + "}"
    if go_type == "*ListNode":
        return f"buildListNode({go_literal(value, '[]int')})"
    if go_type == "*TreeNode":
        return f"buildTreeNode({go_any_array(value)})"
    raise ValueError(f"unsupported Go type: {go_type}")


def go_any(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return go_string(value)
    if isinstance(value, list):
        return go_any_array(value)
    return str(value)


def go_any_array(items):
    return "[]any{" + ", ".join(go_any(item) for item in items) + "}"


def decode_arg(raw: str, go_type: str) -> str:
    if go_type == "string":
        return go_literal(json.loads(raw), go_type)
    if go_type in {"int", "int32", "int64", "uint", "uint32", "uint64", "float32", "float64", "bool"}:
        return go_literal(json.loads(raw), go_type)
    if go_type.startswith("[]") or go_type in {"*ListNode", "*TreeNode"}:
        return go_literal(json.loads(raw), go_type)
    raise ValueError(f"unsupported Go type: {go_type}")


def helper_blocks(param_types: set[str]) -> list[str]:
    blocks = []
    if "*ListNode" in param_types:
        blocks.append(
            """
func buildListNode(values []int) *ListNode {
\tvar head *ListNode
\tvar tail *ListNode
\tfor _, value := range values {
\t\tnode := &ListNode{Val: value}
\t\tif head == nil {
\t\t\thead = node
\t\t\ttail = node
\t\t\tcontinue
\t\t}
\t\ttail.Next = node
\t\ttail = node
\t}
\treturn head
}
""".strip()
        )

    if "*TreeNode" in param_types:
        blocks.append(
            """
func buildTreeNode(values []any) *TreeNode {
\tif len(values) == 0 || values[0] == nil {
\t\treturn nil
\t}

\troot := &TreeNode{Val: values[0].(int)}
\tqueue := []*TreeNode{root}
\tindex := 1

\tfor len(queue) > 0 && index < len(values) {
\t\tnode := queue[0]
\t\tqueue = queue[1:]

\t\tif index < len(values) && values[index] != nil {
\t\t\tnode.Left = &TreeNode{Val: values[index].(int)}
\t\t\tqueue = append(queue, node.Left)
\t\t}
\t\tindex++

\t\tif index < len(values) && values[index] != nil {
\t\t\tnode.Right = &TreeNode{Val: values[index].(int)}
\t\t\tqueue = append(queue, node.Right)
\t\t}
\t\tindex++
\t}

\treturn root
}
""".strip()
        )
    return blocks


def render_body(func_name: str, params, raw_case: list[str], return_type: str, log_func: str) -> str:
    names = []
    lines = []
    for (param_name, param_type), raw in zip(params, raw_case):
        expr = decode_arg(raw, param_type)
        names.append(param_name)
        lines.append(f"\t{param_name} := {expr}")

    call = f"{func_name}({', '.join(names)})"
    if return_type:
        lines.append(f"\tgot := {call}")
        lines.append(f'\t{log_func}("got = %#v", got)')
    else:
        lines.append(f"\t{call}")
        lines.append(f'\t{log_func}("function executed")')

    return "\n".join(lines)


def render_main(main_go: Path, test_data: Path, target: Path):
    func_name, params, return_type = parse_signature(main_go)

    if func_name == "Constructor":
        target.write_text(
            f"{AUTO_MARKER}\npackage main\n\nimport \"fmt\"\n\nfunc main() {{\n\tfmt.Println(\"Design problem: manually test in main.go if needed\")\n}}\n"
        )
        return

    cases = parse_cases(test_data, len(params))
    param_types = {param_type for _, param_type in params}

    sections = [
        AUTO_MARKER,
        "package main",
        "",
        'import "fmt"',
        "",
    ]

    helpers = helper_blocks(param_types)
    if helpers:
        sections.append("\n\n".join(helpers))
        sections.append("")

    first_case = cases[0] if cases else []
    sections.append("func main() {")
    sections.append(render_body(func_name, params, first_case, return_type, "fmt.Printf"))
    sections.append("}")

    target.write_text("\n".join(sections))
    subprocess.run(["gofmt", "-w", str(target)], check=True)


def render_tests(main_go: Path, test_data: Path, target: Path):
    func_name, params, return_type = parse_signature(main_go)

    if func_name == "Constructor":
        target.write_text(
            f"{AUTO_MARKER}\npackage main\n\nimport \"testing\"\n\nfunc TestDebug(t *testing.T) {{\n\t{PLACEHOLDER_SKIP}\n}}\n\nfunc TestSamples(t *testing.T) {{\n\t{PLACEHOLDER_SKIP}\n}}\n"
        )
        return

    cases = parse_cases(test_data, len(params))
    param_types = {param_type for _, param_type in params}

    sections = [
        AUTO_MARKER,
        "package main",
        "",
        'import "testing"',
        "",
    ]

    helpers = helper_blocks(param_types)
    if helpers:
        sections.append("\n\n".join(helpers))
        sections.append("")

    first_case = cases[0] if cases else []
    sections.append("func TestDebug(t *testing.T) {")
    sections.append(render_body(func_name, params, first_case, return_type, "t.Logf"))
    sections.append("}")
    sections.append("")

    sections.append("func TestSamples(t *testing.T) {")
    if not cases:
        sections.append('\tt.Skip("no sample cases found in solution.tests.dat")')
    else:
        for index, raw_case in enumerate(cases, start=1):
            sections.append(f'\tt.Run("sample_{index}", func(t *testing.T) {{')
            body = render_body(func_name, params, raw_case, return_type, "t.Logf")
            sections.append("\n".join(f"\t{line}" if line else "" for line in body.splitlines()))
            sections.append("\t})")
    sections.append("}")
    sections.append("")

    target.write_text("\n".join(sections))
    subprocess.run(["gofmt", "-w", str(target)], check=True)


def should_overwrite(target: Path) -> bool:
    if not target.exists():
        return True
    content = target.read_text()
    return AUTO_MARKER in content or PLACEHOLDER_SKIP in content


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate-go-tests.py <problem-dir>")

    problem_dir = Path(sys.argv[1]).resolve()
    solution_go = problem_dir / "solution.go"
    test_data = problem_dir / "solution.tests.dat"
    main_go = problem_dir / "main.go"
    test_go = problem_dir / "solution_test.go"

    if not solution_go.exists() or not test_data.exists():
        raise SystemExit(f"missing solution.go or solution.tests.dat in {problem_dir}")

    if should_overwrite(main_go):
        render_main(solution_go, test_data, main_go)
        print(f"generated {main_go}")

    if should_overwrite(test_go):
        render_tests(solution_go, test_data, test_go)
        print(f"generated {test_go}")


if __name__ == "__main__":
    main()
