// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	s1 := "great"
	s2 := "rgeat"
	got := isScramble(s1, s2)
	fmt.Printf("got = %#v", got)
}
