// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	s1 := "great"
	s2 := "rgeat"
	got := isScramble(s1, s2)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		s1 := "great"
		s2 := "rgeat"
		got := isScramble(s1, s2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		s1 := "abcde"
		s2 := "caebd"
		got := isScramble(s1, s2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		s1 := "a"
		s2 := "a"
		got := isScramble(s1, s2)
		t.Logf("got = %#v", got)
	})
}
