// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums := []int{0, 1, 0, 3, 12}
	moveZeroes(nums)
	t.Logf("function executed")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums := []int{0, 1, 0, 3, 12}
		moveZeroes(nums)
		t.Logf("function executed")
	})
	t.Run("sample_2", func(t *testing.T) {
		nums := []int{0}
		moveZeroes(nums)
		t.Logf("function executed")
	})
}
