// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums := []int{1, 2, 1}
	got := nextGreaterElements(nums)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums := []int{1, 2, 1}
		got := nextGreaterElements(nums)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums := []int{1, 2, 3, 4, 3}
		got := nextGreaterElements(nums)
		t.Logf("got = %#v", got)
	})
}
