// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums := []int{2, 7, 11, 15}
	target := 9
	got := twoSum(nums, target)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums := []int{2, 7, 11, 15}
		target := 9
		got := twoSum(nums, target)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums := []int{3, 2, 4}
		target := 6
		got := twoSum(nums, target)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		nums := []int{3, 3}
		target := 6
		got := twoSum(nums, target)
		t.Logf("got = %#v", got)
	})
}
