// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	k := 2
	prices := []int{2, 4, 1}
	got := maxProfit(k, prices)
	fmt.Printf("got = %#v", got)
}
