// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	k := 2
	prices := []int{2, 4, 1}
	got := maxProfit(k, prices)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		k := 2
		prices := []int{2, 4, 1}
		got := maxProfit(k, prices)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		k := 2
		prices := []int{3, 2, 6, 5, 0, 3}
		got := maxProfit(k, prices)
		t.Logf("got = %#v", got)
	})
}
