// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	ransomNote := "a"
	magazine := "b"
	got := canConstruct(ransomNote, magazine)
	t.Logf("got = %#v", got)
	t.Log("Edit this test case first when debugging.")
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		ransomNote := "a"
		magazine := "b"
		got := canConstruct(ransomNote, magazine)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		ransomNote := "aa"
		magazine := "ab"
		got := canConstruct(ransomNote, magazine)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		ransomNote := "aa"
		magazine := "aab"
		got := canConstruct(ransomNote, magazine)
		t.Logf("got = %#v", got)
	})
}
