// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	s1 := "abcde"
	s2 := "ace"
	got := longestCommonSubsequence(s1, s2)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		s1 := "abcde"
		s2 := "ace"
		got := longestCommonSubsequence(s1, s2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		s1 := "abc"
		s2 := "abc"
		got := longestCommonSubsequence(s1, s2)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		s1 := "abc"
		s2 := "def"
		got := longestCommonSubsequence(s1, s2)
		t.Logf("got = %#v", got)
	})
}
