// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	s := "rabbbit"
	t := "rabbit"
	got := numDistinct(s, t)
	fmt.Printf("got = %#v", got)
}
