// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	s := "rabbbit"
	t := "rabbit"
	got := numDistinct(s, t)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		s := "rabbbit"
		t := "rabbit"
		got := numDistinct(s, t)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		s := "babgbag"
		t := "bag"
		got := numDistinct(s, t)
		t.Logf("got = %#v", got)
	})
}
