// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	prices := []int{1, 2, 3, 0, 2}
	got := maxProfit(prices)
	fmt.Printf("got = %#v", got)
}
