// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	prices := []int{1, 2, 3, 0, 2}
	got := maxProfit(prices)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		prices := []int{1, 2, 3, 0, 2}
		got := maxProfit(prices)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		prices := []int{1}
		got := maxProfit(prices)
		t.Logf("got = %#v", got)
	})
}
